//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonent()
        {
            this.EquIpInstall = new HashSet<EquIpInstall>();
            this.Request = new HashSet<Request>();
        }
    
        public int AbonentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronumic { get; set; }
        public int Gender { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string PhoneNumber { get; set; }
        public string Mail { get; set; }
        public string Adress { get; set; }
        public int AdressFact { get; set; }
        public string SeriesPasport { get; set; }
        public string NumberPaspotr { get; set; }
        public string DivisionCode { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime DateIssue { get; set; }
        public string AbonentNomer { get; set; }
    
        public virtual FactAdress FactAdress { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquIpInstall> EquIpInstall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
