//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonent()
        {
            this.Request = new HashSet<Request>();
            this.Services1 = new HashSet<Services>();
        }
    
        public string AbonentNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronumic { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string PhoneNumber { get; set; }
        public string Mail { get; set; }
        public string Adress { get; set; }
        public string AdressFact { get; set; }
        public int District { get; set; }
        public string SeriesPasport { get; set; }
        public string NumberPaspotrNumberPaspotr { get; set; }
        public string DivisionCode { get; set; }
        public string IssuedBy { get; set; }
        public string DateIssue { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ConclusionDate { get; set; }
        public string ContractType { get; set; }
        public string TerminationReason { get; set; }
        public string PersonalAccount { get; set; }
        public string Services { get; set; }
        public int EquipmentID { get; set; }
    
        public virtual District District1 { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services1 { get; set; }
    }
}
