//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConectService
    {
        public int ConnectedServiceID { get; set; }
        public int AbonentID { get; set; }
        public int ServicesID { get; set; }
        public Nullable<System.DateTime> ConnectionDate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Services Services { get; set; }
    }
}
