//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Abonent = new HashSet<Abonent>();
            this.EquipmentInPoint = new HashSet<EquipmentInPoint>();
            this.MacAndIP = new HashSet<MacAndIP>();
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
        }
    
        public string SerialNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public int IDequipment { get; set; }
        public Nullable<int> ListPhone { get; set; }
        public Nullable<int> PortInform { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent> Abonent { get; set; }
        public virtual PortType PortType { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentInPoint> EquipmentInPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MacAndIP> MacAndIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
