//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquIpInstall
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> StaffID { get; set; }
        public int Equip { get; set; }
        public int AbonentID { get; set; }
        public string Discription { get; set; }
        public bool Rental { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
