//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentInPoint
    {
        public int ID { get; set; }
        public int IDequipment { get; set; }
        public System.DateTime DateSetting { get; set; }
        public int Position { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual PositionInform PositionInform { get; set; }
    }
}
