//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IP()
        {
            this.MacAndIP = new HashSet<MacAndIP>();
        }
    
        public int ID { get; set; }
        public string Ipv4 { get; set; }
        public Nullable<System.DateTime> StartV4 { get; set; }
        public Nullable<System.DateTime> EndV4 { get; set; }
        public string Ipv6 { get; set; }
        public Nullable<System.DateTime> StartV6 { get; set; }
        public Nullable<System.DateTime> EndV6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MacAndIP> MacAndIP { get; set; }
    }
}
