//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacAndIP
    {
        public int IDequipment { get; set; }
        public int IDMac { get; set; }
        public int iP { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual IP IP1 { get; set; }
        public virtual Mac Mac { get; set; }
    }
}
