//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulsForRole
    {
        public int IDRole { get; set; }
        public int IDMFR { get; set; }
        public int IDModules { get; set; }
    
        public virtual Moduls Moduls { get; set; }
        public virtual Role Role { get; set; }
    }
}
