//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionInform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionInform()
        {
            this.EquipmentInPoint = new HashSet<EquipmentInPoint>();
        }
    
        public int ID { get; set; }
        public string Adress { get; set; }
        public string Position { get; set; }
        public string ConectionPoint { get; set; }
        public string GeoPosition { get; set; }
        public int District { get; set; }
    
        public virtual District District1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentInPoint> EquipmentInPoint { get; set; }
    }
}
