//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public string RequestNum { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Servise { get; set; }
        public int ServiseType { get; set; }
        public int ServiseView { get; set; }
        public int State { get; set; }
        public int ProblemType { get; set; }
        public string Description { get; set; }
        public string ContractNumber { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual ProblemType ProblemType1 { get; set; }
        public virtual RequestService RequestService { get; set; }
        public virtual Services Services { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ServiceView ServiceView { get; set; }
        public virtual State State1 { get; set; }
    }
}
