//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTypeService
    {
        public int ID { get; set; }
        public int TypeService { get; set; }
        public int ServiceView { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual ServiceView ServiceView1 { get; set; }
    }
}
